apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
    deployment: blue
    version: 1.0.0 # concept of version could be important for your CD tools. 
spec: # here's what the deployment is going to create
  replicas: 1
  selector:
    matchLabels:
      app: flask
      deployment: blue # including blue key/value
      version: 1.0.0 # version (optional)
  template: 
    metadata:
      labels:
        app: flask
        deployment: blue
        version: 1.0.0 # concept of version could be important for your CD tools. 
    spec:
      containers:
      - name: flask
        image: 648503940051.dkr.ecr.us-east-2.amazonaws.com/my-project-repo
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---

