apiVersion: apps/v1
kind: Deployment
metadata:
  name: fllask
  labels:
    app: fllask
    deployment: blue
    version: 1.0.0 # concept of version could be important for your CD tools. 
spec: # here's what the deployment is going to create
  replicas: 1
  selector:
    matchLabels:
      app: fllask
      deployment: blue # including blue key/value
      version: 1.0.0 # version (optional)
  template: 
    metadata:
      labels:
        app: fllask
        deployment: blue
        version: 1.0.0 # concept of version could be important for your CD tools. 
    spec:
      containers:
      - name: fllask
        image: 524472057840.dkr.ecr.us-east-2.amazonaws.com/project2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
