apiVersion: apps/v1
kind: Deployment
metadata:
  name: Fllask
  labels:
    app: Fllask
    deployment: blue
    version: 1.0.0 # concept of version could be important for your CD tools. 
spec: # here's what the deployment is going to create
  replicas: 1
  selector:
    matchLabels:
      app: Fllask
      deployment: blue # including blue key/value
      version: 1.0.0 # version (optional)
  template: 
    metadata:
      labels:
        app: Fllask
        deployment: blue
        version: 1.0.0 # concept of version could be important for your CD tools. 
    spec:
      containers:
      - name: Fllask
        image: 648503940051.dkr.ecr.us-east-2.amazonaws.com/my-project-repo
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: Fllask-service
  labels:
    name: Fllask-service
spec:
  type: LoadBalancer
  selector: # scans for deployments that match this selector (this is the green!)
    app: Fllask # this is the updated deployment to use
    deployment: blue
    version: 1.0.0 # new version
  ports:
  - name: http 
    port: 80
    targetPort: 5000
