apiVersion: v1
kind: Service
metadata:
  name: fllask-service
  labels:
    name: fllask-service
spec:
  type: LoadBalancer
  selector: # scans for deployments that match this selector (this is the green!)
    app: fllask-green # this is the updated deployment to use
    deployment: green
    version: 1.0.1 # new version
  ports:
  - name: http 
    port: 80
    targetPort: 5000


